### ISSUE TITLE
Sf 2.8.6 , multisite-bundle 0.1.1 is breaking the debugtoolbar 

### ISSUE THREAD

**Issue by delphimat** [alexandresalome/multisite-bundle#16]
Hi.

It's my first issues , i hope it will help the community.

the error 

`The profiler template "@WebProfiler/Collector/request.html.twig" for data collector "request" does not exist.
500 Internal Server Error - UnexpectedValueException`

From what i see in the xdebug.

WebProfilerBundle/Profiler/TemplateManager.php  l : 125  : 
The problem is at this line.

`$loader = $this->twig->getLoader();`

When the framework want to check if the template "@WebProfiler/Collector/request.html.twig" is loaded.

The code is looking in the wrong  loader

He should have a look inside the loader "Sf\Bundle\TwigBundle\Loader\FilesystemLoader"

And now he is looking inside "Alex\MultiwebsiteBundle\Twig\MultisteLoader".
which this one have a paths array empty.

I can hart fix it , but it's ugly, tell me.
How can i help you to fixe this issue :) 

thanks.

**Comment by delphimat** [comment]
To resume when profiler try to check in the class MultisiteLoader .

the var  Paths is not update, then the process dont find the location and thrown an exception

**Comment by giovkanata** [comment]
@alexandresalome Same problem here with Symfony 2.8.6 (on 3.0.6 it doesn't work at all).

**Comment by sanderborgman** [comment]
Fixed in #18
