### ISSUE TITLE
Symfony 3 Compatibility issue.

### ISSUE THREAD

**Issue by giovkanata** [alexandresalome/multisite-bundle#17]
I would like to make this bundle working with Symfony 3 and trying on a fresh installation in locale (*obviously I've updated the composer.json on my new branch 3.0 to allow Symfony 3*) at the first attempt I got:
```
UndefinedMethodException,
Attempted to call an undefined method named "setSiteContext"
of class "Symfony\Bundle\FrameworkBundle\Routing\Router".
Did you mean to call "setContext"?
```
The problem comes from the compiler pass ```Alex\MultisiteBundle\DependencyInjection\Compiler\InjectSiteContextPass```
it appens during the execution of
 ```$container->findDefinition('router.default')->addMethodCall('setSiteContext', array(new Reference('site_context')));```

On another fresh installation with Symfony 2.8.6 this problem not appear but after passed some time reading all the docs about Routing, Compiler Pass, DI, etc (from Symfony 2.8.6. to 3.0.6) I haven't noticed difference related to this, but maybe I've missed something.

There is someone can point me in the right direction to resolve the problem?

**Comment by sanderborgman** [comment]
Fixed in #18
